function Mat = RotMat(Axis,Angle)

switch Axis
    case 'x'
        Mat = [1,0,0;...
            0,cos(Angle),-sin(Angle);...
            0,sin(Angle),cos(Angle)];
    case 'y'
        Mat = [cos(Angle),0,sin(Angle);...
            0,1,0;...
            -sin(Angle),0,cos(Angle)];
    case 'z'
        Mat = [cos(Angle),-sin(Angle),0;...
            sin(Angle),cos(Angle),0;...
            0,0,1];
    otherwise
        error('Enter string x,y,or z');
end